name: create-release
on: push

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Version
        run: |
          version=$(cat VERSION)
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Create Release Branch
        run: |
          git checkout -b release/v${{ env.VERSION }}
      - name: Set Version
        run: |
          sed -i "s/config\/version=\"[a-zA-Z0-9_\.\-]*\"/config\/version=\"${{ env.VERSION }}\"/g" project.godot
          sed -i "s/version=\"[a-zA-Z0-9_\.\-]*\"/version=\"${{ env.VERSION }}\"/g" addons/j_test/plugin.cfg
          gh auth setup-git
          git add project.godot addons/j_test/plugin.cfg
          git commit -m "Set version to v${{ env.VERSION }}"
      - name: Push Release Branch
        run: |
          git push origin release/v${{ env.VERSION }}
      - name: Create Release Archive
        run: git archive --format zip --output "jTest_v${{ env.VERSION }}.zip" HEAD
      - name: Create Release Draft
        run: >-
          gh release create "v${{ env.VERSION }}"
          "jTest_v${{ env.VERSION }}.zip"
          --draft
          --title "v${{ env.VERSION }}"
          --notes-file CHANGELOG.md
